export const SAVE_PRODUCT_REQUEST = "SAVE_PRODUCT_REQUEST";
export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const ADJUST_QTY = "ADJUST_QTY";
